# Generated by Django 5.0.4 on 2024-05-11 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0002_fournisseur_produitnc_product_fournisseur'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasin.commande')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasin.product')),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='products',
            field=models.ManyToManyField(through='magasin.CommandeItem', to='magasin.product'),
        ),
    ]
