# Generated by Django 5.0.4 on 2024-05-11 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0003_commandeitem_commande_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fournisseur',
            old_name='adressse',
            new_name='adresse',
        ),
        migrations.RenameField(
            model_name='produitnc',
            old_name='Duree_garantie',
            new_name='duree_garantie',
        ),
        migrations.AlterField(
            model_name='commande',
            name='items',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='commande',
            name='pays',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='commande',
            name='products',
            field=models.ManyToManyField(related_name='commandes', through='magasin.CommandeItem', to='magasin.product'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='commande',
            name='zipcode',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='telephone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='magasin.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
